name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: clone project
        uses: actions/checkout@v2
      - name: Build
        run: |
          yarn
          yarn build
      - name: deploy build
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-a"
          SOURCE: "build"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
